ifndef TOP
	TOP = ../..
endif

include $(TOP)/make.include

INCLUDE_DIR += -I$(TOP)/include

SOURCES += ionapi.c

TARGET = $(TOP)/lib/libion.a

include $(TOP)/Makefile.in


#CFLAGS += $(DEFINES) $(MYDEFS)
#CFLAGS += -I../../Include
#CFLAGS += -I../../../../common/IPC/include

