TOP ?= ..

include $(TOP)/make.include

#---------------------------------------
# Target definition (User)
#---------------------------------------
TARGET := $(LIB_DIR)/libosal

SOURCES		+= pli.c threads.cpp

SHARED_LIB=1
include $(TOP)/Makefile.in
